SET DEFINE OFF
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('Costco', 1201301200, 'A', 'cash', 3, 'USD');
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('Walmart', 1201301201, 'A', 'cash', 8, 'USD');
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('Wayfair', 1201301202, 'A', 'cash', 9, 'USD');
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('Pricerite', 1201301203, 'A', 'cheque', 10, 'USD');
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('BestBuy', 1201301204, 'A', 'cheque', 11, 'USD');
INSERT INTO ADMIN.VENDOR (VENDOR_NAME, ACC_NUM, STATUS, PAYMENT_METHOD, USER_ID, CURRENCY) 
VALUES ('Staples', 1201301205, 'A', 'cheque', 12, 'USD');

COMMIT;
