
-- Purchase Order insert
SET DEFINE OFF
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (1, 1, to_date('02-Jan-23', 'DD-MON-RR'), 'completed', 1000);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (2, 5, to_date('05-Jan-23', 'DD-MON-RR'), 'completed', 5000);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (3, 1, to_date('07-Jan-23', 'DD-MON-RR'), 'completed', 1000);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (4, 1, to_date('12-Jan-23', 'DD-MON-RR'), 'completed', 1000);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (5, 2, to_date('02-Feb-23', 'DD-MON-RR'), 'completed', 2000);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (5, 1, to_date('02-Feb-23', 'DD-MON-RR'), 'completed', 1750);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (6, 3, to_date('04-Feb-23', 'DD-MON-RR'), 'completed', 1500);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (7, 4, to_date('10-Feb-23', 'DD-MON-RR'), 'completed', 250);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (7, 5, to_date('10-Feb-23', 'DD-MON-RR'), 'completed', 250);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (8, 5, to_date('12-Feb-23', 'DD-MON-RR'), 'completed', 500);
INSERT INTO ADMIN.PURCHASE_ORDER_HEADER (REQ_ID, VENDOR_ID, PO_DATE, PO_STATUS, PO_TOTAL) 
VALUES (9, 5, to_date('15-Feb-23', 'DD-MON-RR'), 'completed', 800);


commit;
