exec pms.usp_item_data('Goods', 'Dell_Laptop', 'Pavilion_edition');
exec pms.usp_item_data ('Non - goods', 'Xerox_machine', 'BlackWhite');
exec pms.usp_item_data('Goods', 'Dell_Notebook', 'PavilionX_edition');
exec pms.usp_item_data('Goods', 'Macbook', 'Pro');
exec pms.usp_item_data('Goods' , 'iPad', 'Pro');
exec pms.usp_item_data('Goods', 'iPad', 'Air');
exec pms.usp_item_data('Goods', 'ASUS_notebook', 'LightSeries');
exec pms.usp_item_data('Goods', 'ASUS_thinkpad', 'Useries');
exec pms.usp_item_data('Goods', 'Lenovo_Laptop', 'Touchscreen');
exec pms.usp_item_data('Goods', 'Lenovo_tab', 'Yogoseries');
exec pms.usp_item_data('Goods', 'HP_laptop', '360Series');
exec pms.usp_item_data('Goods', 'HP_Printers', 'Colour');
exec pms.usp_item_data('Non - goods', 'chair', 'furniture');
exec pms.usp_item_data('Non - goods', 'desk', 'furniture');
exec pms.usp_item_data('Non - goods', 'Locker', 'furniture');
exec pms.usp_item_data('Goods', 'Microsoft_laptop', 'Kseries');
exec pms.usp_item_data('Goods', 'Samsung_Laptop', 'Pro');
exec pms.usp_item_data('Goods', 'TV', 'OLED');