SET DEFINE OFF
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (4000, 'BUSINESS CAPITAL ACCOUNT', 'CAPITAL');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (2000, 'BUSINESS LIABILITY ACCOUNT', 'LIABILITY');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (1000, 'BUSINESS CASH ACCOUNT', 'ASSET');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (1001, 'BUSINESS BANK ACCOUNT', 'ASSET');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (1002, 'BUSINESS FURNITURE ACCOUNT', 'ASSET');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (1003, 'BUSINESS STATIONARY ACCOUNT', 'ASSET');
INSERT INTO ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE) 
VALUES (1004, 'BUSINESS GOODS ACCOUNT', 'ASSET');


COMMIT;