
UPDATE admin.journal_header set status='POST';

SET DEFINE OFF
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (1, 1, 1000, to_date('1-Jan-23', 'DD-MON-RR'), 'Debit', 50000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (1, 2, 1001, to_date('1-Jan-23', 'DD-MON-RR'), 'Debit', 50000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (1, 3, 4000, to_date('1-Jan-23', 'DD-MON-RR'), 'Credit', -100000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (2, 4, 1002, to_date('4-Jan-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (2, 5, 1000, to_date('4-Jan-23', 'DD-MON-RR'), 'Credit', -5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (3, 6, 1003, to_date('7-Jan-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (3, 7, 1001, to_date('7-Jan-23', 'DD-MON-RR'), 'Credit', -5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (4, 8, 1004, to_date('9-Jan-23', 'DD-MON-RR'), 'Debit', 2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (4, 9, 1000, to_date('9-Jan-23', 'DD-MON-RR'), 'Credit', -2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (5, 10, 1000, to_date('11-Jan-23', 'DD-MON-RR'), 'Debit', 3000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (5, 11, 1004, to_date('11-Jan-23', 'DD-MON-RR'), 'Credit', -2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (5, 12, 4000, to_date('11-Jan-23', 'DD-MON-RR'), 'Credit', -1000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (6, 13, 1004, to_date('14-Jan-23', 'DD-MON-RR'), 'Debit', 10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (6, 14, 2000, to_date('14-Jan-23', 'DD-MON-RR'), 'Credit', -10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (7, 15, 2000, to_date('27-Jan-23', 'DD-MON-RR'), 'Debit', 10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (7, 16, 1000, to_date('27-Jan-23', 'DD-MON-RR'), 'Credit', -10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (8, 17, 1000, to_date('28-Jan-23', 'DD-MON-RR'), 'Debit', 8000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (8, 18, 1004, to_date('28-Jan-23', 'DD-MON-RR'), 'Credit', -5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (8, 19, 4000, to_date('28-Jan-23', 'DD-MON-RR'), 'Credit', -3000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (9, 20, 4000, to_date('29-Jan-23', 'DD-MON-RR'), 'Debit', 10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (9, 21, 1000, to_date('29-Jan-23', 'DD-MON-RR'), 'Credit', -10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 22, 1000, to_date('1-Feb-23', 'DD-MON-RR'), 'Debit', 34000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 23, 1001, to_date('1-Feb-23', 'DD-MON-RR'), 'Debit', 45000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 24, 1002, to_date('1-Feb-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 25, 1003, to_date('1-Feb-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 26, 1004, to_date('1-Feb-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (10, 27, 4000, to_date('1-Feb-23', 'DD-MON-RR'), 'Credit', -94000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (11, 28, 1004, to_date('4-Feb-23', 'DD-MON-RR'), 'Debit', 15000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (11, 29, 1000, to_date('4-Feb-23', 'DD-MON-RR'), 'Credit', -15000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (12, 30, 1004, to_date('6-Feb-23', 'DD-MON-RR'), 'Debit', 2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (12, 31, 1000, to_date('6-Feb-23', 'DD-MON-RR'), 'Credit', -2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (13, 32, 1000, to_date('7-Feb-23', 'DD-MON-RR'), 'Debit', 3000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (13, 33, 1004, to_date('7-Feb-23', 'DD-MON-RR'), 'Credit', -2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (13, 34, 4000, to_date('7-Feb-23', 'DD-MON-RR'), 'Credit', -1000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (14, 35, 1004, to_date('12-Feb-23', 'DD-MON-RR'), 'Debit', 1500);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (14, 36, 1001, to_date('12-Feb-23', 'DD-MON-RR'), 'Credit', -1500);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (15, 37, 1003, to_date('14-Feb-23', 'DD-MON-RR'), 'Debit', 2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (15, 38, 1001, to_date('14-Feb-23', 'DD-MON-RR'), 'Credit', -2000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (16, 39, 1004, to_date('17-Feb-23', 'DD-MON-RR'), 'Debit', 3200);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (16, 40, 2000, to_date('17-Feb-23', 'DD-MON-RR'), 'Credit', -3200);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (17, 41, 2000, to_date('27-Feb-23', 'DD-MON-RR'), 'Debit', 3200);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (17, 42, 1001, to_date('27-Feb-23', 'DD-MON-RR'), 'Credit', -3200);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (18, 43, 4000, to_date('28-Feb-23', 'DD-MON-RR'), 'Debit', 10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (18, 44, 1001, to_date('28-Feb-23', 'DD-MON-RR'), 'Credit', -10000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 45, 1000, to_date('1-Mar-23', 'DD-MON-RR'), 'Debit', 20000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 46, 1001, to_date('1-Mar-23', 'DD-MON-RR'), 'Debit', 28300);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 47, 1002, to_date('1-Mar-23', 'DD-MON-RR'), 'Debit', 5000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 48, 1003, to_date('1-Mar-23', 'DD-MON-RR'), 'Debit', 7000);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 49, 1004, to_date('1-Mar-23', 'DD-MON-RR'), 'Debit', 24700);
INSERT INTO ADMIN.LEDGER (JRNL_ID, JRNL_LINE_NO, ACCOUNT_ID, ACCOUNTING_DATE, TRANSACTION_FLAG, AMOUNT) 
VALUES (19, 50, 4000, to_date('1-Mar-23', 'DD-MON-RR'), 'Credit', -85000);

COMMIT;
