/* Requisitions create */
SET DEFINE OFF
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase nongoods chair(5 qty) and Desk Furniture(5 qty)(CASH) for office use', to_date('02-Jan-23', 'DD-MON-RR'), 'true', to_date('02-Jan-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase nongoods Xerox Machine(1 qty)(Bank) for 5000', to_date('05-Jan-23', 'DD-MON-RR'), 'true', to_date('05-Jan-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods Macbook Air (2 qty) Laptop (CASH) for 2000', to_date('07-Jan-23', 'DD-MON-RR'), 'true', to_date('07-Jan-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods Apple Ipad Pro (10 qty)& Asus ThinkPad (10 qty)(for Credit) for 10,000', to_date('12-Jan-23', 'DD-MON-RR'), 'true', to_date('12-Jan-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods TV(1),Ipad Pro(4ty),Macbook Air (10 qty)(CASH) for 15000', to_date('02-Feb-23', 'DD-MON-RR'), 'true', to_date('02-Feb-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods HP Laptop(2 qty) and Printer(1 qty)(CASH) of 2000', to_date('04-Feb-23', 'DD-MON-RR'), 'true', to_date('04-Feb-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods(1500 - Bank Payment) ASUS notebook (3 qty)& thinkpad(3 qty)', to_date('10-Feb-23', 'DD-MON-RR'), 'true', to_date('10-Feb-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase nongoods (2000 - Bank Payment ) Locker (4 qty)', to_date('12-Feb-23', 'DD-MON-RR'), 'true', to_date('12-Feb-23', 'DD-MON-RR'));
INSERT INTO ADMIN.REQUISITION_HEADER (REQ_APPROVER_ID, REQ_CREATOR_ID, REQ_STATUS, REQ_DESC, APPROVAL_DATE, BUDGET_CHECK, REQ_CREATED) 
VALUES (1, 2, 'approved', 'Purchase goods (3200 $) Macbook Pro on Credit(4 qty)', to_date('15-Feb-23', 'DD-MON-RR'), 'true', to_date('15-Feb-23', 'DD-MON-RR'));

/* Requisition line create */

SET DEFINE OFF
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (1, 14, 5);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (1, 15, 5);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (2, 2, 1);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (3, 4, 2);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (4, 6, 10);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (4, 9, 10);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (5, 19, 1);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (5, 6, 4);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (5, 4, 10);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (6, 12, 2);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (6, 13, 1);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (7, 8, 3);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (7, 20, 3);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (8, 16, 4);
INSERT INTO ADMIN.REQUISITION_LINE (REQ_ID, ITEM_VENDOR_ID, QUANTITY) 
VALUES (9, 5, 4);


commit;