SET DEFINE OFF

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8573130698, 'hughjackman@gmail.com', 'A', 1);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8514540231, 'Nicole@hotmail.com', 'A', 2);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8573130202, 'janedoe@gmail.com', 'A', 3);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8573130605, 'Jonny@yahoo.com', 'A', 4);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8546160202, 'Chrishems@hotmail.com', 'A', 5);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142323, 'jessica@yahoo.com', 'A', 6);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142324, 'AjitPatil@gmail.com', 'A', 7);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142325, 'DougM@yahoo.com', 'A', 8);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142326, 'NeerajShah@hotmail.com', 'A', 9);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142327, 'Joseph@outlook.com', 'A', 10);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142328, 'coriebarry@gmail.com', 'A', 11);

INSERT INTO ADMIN.CONTACT (PHONE_NO, EMAIL, STATUS, ACTOR_ID) 
VALUES (8574142329, 'JohnLed@yahoo.com', 'A', 12);

COMMIT;