SET DEFINE OFF
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('01-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('04-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('07-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('09-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('11-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('14-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('27-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('28-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('29-JAN-23', 'DD-MON-RR'), 2023, 1, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('01-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('04-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('06-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('07-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('12-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('14-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('17-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('27-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('28-FEB-23', 'DD-MON-RR'), 2023, 2, 'Open');
INSERT INTO ADMIN.JOURNAL_HEADER (JRNL_DATE, FISCAL_YEAR, ACCOUNTING_PERIOD, STATUS) 
VALUES (to_date('01-MAR-23', 'DD-MON-RR'), 2023, 3, 'Open');

COMMIT;