SET DEFINE OFF

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Main Street', 'MA', 2115, 'A', 1);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Elm Street', 'MA', 2215, 'A', 2);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Maple Ave', 'MA', 3640, 'A', 3);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Oak Street', 'MA', 5501, 'A', 4);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Pine St', 'MA', 1125, 'A', 5);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Cedar Rd', 'MA', 9874, 'A', 6);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Chestnut St', 'MA', 4751, 'A', 7);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Cherry Street', 'MA', 4851, 'A', 8);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Birch Ave', 'MA', 4951, 'A', 9);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Mission park', 'MA', 41051, 'A', 10);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Spruce Street', 'MA', 41151, 'A', 11);

INSERT INTO ADMIN.ADDRESS (STREET, STATE, ZIPCODE, STATUS, ACTOR_ID) 
VALUES ('Peach street', 'MA', 41251, 'A', 12);

COMMIT;